apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ph-ee-connector-channel
  title: Channel Connector
  description: A PH connector that initiates transactions through Zeebe.
  annotations:
    github.com/project-slug: one-acre-fund/ph-ee-connector-channel
    backstage.io/kubernetes-id: ph-ee-connector-channel
    backstage.io/kubernetes-namespace: paymenthub
    backstage.io/techdocs-ref: dir:.
    sonarqube.org/project-key: one-acre-fund_ph-ee-connector-channel
    backstage.io/code-coverage: sonarqube
  tags:
    - java
    - spring-boot
    - apache-camel
    - payment-hub
    - paymenthub
    - operations
  links:
    - url: https://sonarcloud.io/project/overview?id=one-acre-fund_ph-ee-connector-channel
      title: Code Quality Dashboard
      icon: dashboard
    - url: https://ph-web.oneacrefund.org
      title: Production Environment
      icon: globe
    - url: https://elastic.oneacrefund.org/app/apm/services/ph-ee-connector-channel
      title: Elastic APM Dashboard
      icon: globe
    - url: https://elastic.oneacrefund.org/app/r/s/CgjiD
      title: Kong Ingress logs
      icon: globe
    - url: https://github.com/one-acre-fund/ph-ee-connector-channel/blob/develop/.github/workflows/build.yaml
      title: Build Pipeline
      icon: build
spec:
  type: service
  lifecycle: production
  owner: group:one-acre-fund/credits-and-payments
  system: connectors
  consumesApis:
    - zeebe-gateway-grpc-api
  dependsOn:
    - resource:default/zeebe-cluster
