operations:
  url: ${OPERATIONS_URL:http://bb-operations.mifos.io/api/v1}
  auth-expiry-default: ${AUTHENTICATION_EXPIRY_DEFAULT:60} # in seconds
  endpoint:
    auth: ${AUTHENTICATION_API:https://accounts.qa.oneacrefund.org/realms/OneAcreFund/protocol/openid-connect/token}
    transfers: "/transfers?page=0&size=1&"
    transactionReq: "/transactionRequests/?"

identity:
  channel:
    clients:
      - clientId: ${CHANNEL_TENANTPRIMARY_CLIENTID:channel-tn03}
        clientSecret: ${CHANNEL_TENANTPRIMARY_CLIENTSECRET:p1234}
        tenant: ${CHANNEL_TENANTPRIMARY_TENANT:tn03}
      - clientId: ${CHANNEL_TENANTSECONDARY_CLIENTID:channel-tn04}
        clientSecret: ${CHANNEL_TENANTSECONDARY_CLIENTSECRET:p1234}
        tenant: ${CHANNEL_TENANTSECONDARY_TENANT:tn04}